### ISSUE TITLE
How to test requirements that verify at most, one value exists in object

### ISSUE THREAD

**Issue by vbudhram** [TryxAPI/lrs-conformance-tests#1]
Ex, A Statement uses the "authority" property at most one time (Multiplicity, 4.1.a)

The javascript JSON parser does not throw any exceptions when parsing strings with multiple values for the same key. The last value for that key is the value that is saved.

**Comment by toaster33** [comment]
Closing for now unless ADL makes requests.  If I recall, issue was brought up and implicit and tests not needed.
