### ISSUE TITLE
Need to run specific tests

### ISSUE THREAD

**Issue by toaster33** [TryxAPI/lrs-conformance-tests#2]
Is it possible to add parameters to command line utility that point to a specific test?

**Comment by HPate-Riptide** [comment]
The only way seems to be with the `-g` or `--grep` command line flags.

For example:
```js
describe('api', function(){
  describe('GET /api/users', function() {
    it('respond with an array of users');
  });
});

describe('app', function(){
  describe('GET /users', function() {
    it('respond with an array of users');
  });
});
```

You could run the `app` tests with the command line flag `-g app` or `--grep app`.  To run just the `GET /users` test you could use `--grep "GET /users"`

**Comment by DavidTPate** [comment]
Is it useful to be able to run specific tests? If the point is to make sure you are conformant, then you want to make sure you are fully conformant not conformant with just one test.

If it's the case that you are updating your LRS to be conformant, you would still want to run all of the tests to make sure you didn't break your conformance so I think it is a non-issue.

**Comment by ryansmith94** [comment]
@DavidTPate if a test fails, what are the chances that you'll fix it first time? Additionally, you may want to rerun that single test to debug the code during the test. I don't want to keep running 1000+ tests between every attempt to fix it and every time I want to debug something.
